apiVersion: apps/v1
kind: Deployment
metadata:
  name: ofer-alpine-nginx
  labels:
    app: ofer-alpine-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ofer-alpine-nginx
  template:
    metadata:
      labels:
        app: ofer-alpine-nginx
    spec:
      containers:
      - name: ofer-alpine-nginx
        image: ofer320/nginx-alpinev1
        ports:
        - containerPort: 80
