apiVersion: apps/v1
kind: Deployment
metadata:
  name: ofer_alpinev1_nginx
  labels:
    app: ofer_alpinev1_nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ofer_alpinev1_nginx
  template:
    metadata:
      labels:
        app: ofer_alpinev1_nginx
    spec:
      containers:
      - name: ofer_alpinev1_nginx
        image: ofer320/nginx-alpinev1
        ports:
        - containerPort: 80
